### ISSUE TITLE
Live demo is offline

### ISSUE THREAD

**Issue by vi** [br-g/Deep-Audio-Visualization#1]
> 404
> There isn't a GitHub Pages site here.

**Comment by br-g** [comment]
Hi Vi,

Thanks for reporting this.
The demo is available with a new URL: [https://br-g.github.io/Deep-Audio-Visualization/web-app](https://br-g.github.io/Deep-Audio-Visualization/web-app).
I have made a request to update the Chrome Experiments's page, but this takes some time.
